# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cf39a375ba3c839d05a48485d31142f03e2d35786f0ce28fe294ad2b01201199605c86bc9902d473409e613ff50242c35bce3d7711c5b24d05518e1d7383a472

test:
  secret_key_base: 0430d784e50733c7eb49cce745ce31c717fdfb8786c8e4eb74b706c935ff7502b3c7eecdfa255489dde84cb4150b2db2de8b57ff544dc08073183417a2d9b74a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
